/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.cmu.cc.slh.jdbc;

import edu.cmu.cc.slh.dao.*;
import edu.cmu.cc.slh.factory.*;
import edu.cmu.cc.slh.dto.*;
import edu.cmu.cc.slh.exceptions.*;

import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class TblHotspotsDaoImpl extends AbstractDAO implements TblHotspotsDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT MID, Coordinates, SID, CID FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( MID, Coordinates, SID, CID ) VALUES ( ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET MID = ?, Coordinates = ?, SID = ?, CID = ? WHERE CID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE CID = ?";

	/** 
	 * Index of column MID
	 */
	protected static final int COLUMN_MID = 1;

	/** 
	 * Index of column Coordinates
	 */
	protected static final int COLUMN_COORDINATES = 2;

	/** 
	 * Index of column SID
	 */
	protected static final int COLUMN_SID = 3;

	/** 
	 * Index of column CID
	 */
	protected static final int COLUMN_CID = 4;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 4;

	/** 
	 * Index of primary-key column CID
	 */
	protected static final int PK_COLUMN_CID = 1;

	/** 
	 * Inserts a new row in the TBL_HotSpots table.
	 */
	public TblHotspotsPk insert(TblHotspots dto) throws TblHotspotsDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT, Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			if (dto.isMidNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getMid() );
			}
		
			stmt.setString( index++, dto.getCoordinates() );
			if (dto.isSidNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getSid() );
			}
		
			stmt.setInt( index++, dto.getCid() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setCid( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TblHotspotsDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the TBL_HotSpots table.
	 */
	public void secupdate(TblHotspots pk, TblHotspots dto) throws TblHotspotsDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			if (dto.isMidNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getMid() );
			}
		
			stmt.setString( index++, dto.getCoordinates() );
			if (dto.isSidNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getSid() );
			}
		
			stmt.setInt( index++, dto.getCid() );
			stmt.setInt( 5, pk.getCid() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TblHotspotsDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the TBL_HotSpots table.
	 */
	public void delete(TblHotspotsPk pk) throws TblHotspotsDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getCid() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TblHotspotsDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the TBL_HotSpots table that matches the specified primary-key value.
	 */
	public TblHotspots findByPrimaryKey(TblHotspotsPk pk) throws TblHotspotsDaoException
	{
		return findByPrimaryKey( pk.getCid() );
	}

	/** 
	 * Returns all rows from the TBL_HotSpots table that match the criteria 'CID = :cid'.
	 */
	public TblHotspots findByPrimaryKey(int cid) throws TblHotspotsDaoException
	{
		TblHotspots ret[] = findByDynamicSelect( SQL_SELECT + " WHERE CID = ?", new Object[] {  new Integer(cid) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the TBL_HotSpots table that match the criteria ''.
	 */
	public TblHotspots[] findAll() throws TblHotspotsDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY CID", null );
	}

	/** 
	 * Returns all rows from the TBL_HotSpots table that match the criteria 'MID = :mid'.
	 */
	public TblHotspots[] findByTblFloormaps(int mid) throws TblHotspotsDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE MID = ?", new Object[] {  new Integer(mid) } );
	}

	/** 
	 * Returns all rows from the TBL_HotSpots table that match the criteria 'SID = :sid'.
	 */
	public TblHotspots[] findByTblCategories(int sid) throws TblHotspotsDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE SID = ?", new Object[] {  new Integer(sid) } );
	}

	/** 
	 * Returns all rows from the TBL_HotSpots table that match the criteria 'MID = :mid'.
	 */
	public TblHotspots[] findWhereMidEquals(int mid) throws TblHotspotsDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE MID = ? ORDER BY MID", new Object[] {  new Integer(mid) } );
	}

	/** 
	 * Returns all rows from the TBL_HotSpots table that match the criteria 'Coordinates = :coordinates'.
	 */
	public TblHotspots[] findWhereCoordinatesEquals(String coordinates) throws TblHotspotsDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Coordinates = ? ORDER BY Coordinates", new Object[] { coordinates } );
	}

	/** 
	 * Returns all rows from the TBL_HotSpots table that match the criteria 'SID = :sid'.
	 */
	public TblHotspots[] findWhereSidEquals(int sid) throws TblHotspotsDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE SID = ? ORDER BY SID", new Object[] {  new Integer(sid) } );
	}

	/** 
	 * Returns all rows from the TBL_HotSpots table that match the criteria 'CID = :cid'.
	 */
	public TblHotspots[] findWhereCidEquals(int cid) throws TblHotspotsDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CID = ? ORDER BY CID", new Object[] {  new Integer(cid) } );
	}

	/**
	 * Method 'TblHotspotsDaoImpl'
	 * 
	 */
	public TblHotspotsDaoImpl()
	{
	}

	/**
	 * Method 'TblHotspotsDaoImpl'
	 * 
	 * @param userConn
	 */
	public TblHotspotsDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "SLH_Web_DB.TBL_HotSpots";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected TblHotspots fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			TblHotspots dto = new TblHotspots();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected TblHotspots[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			TblHotspots dto = new TblHotspots();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		TblHotspots ret[] = new TblHotspots[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(TblHotspots dto, ResultSet rs) throws SQLException
	{
		dto.setMid( rs.getInt( COLUMN_MID ) );
		if (rs.wasNull()) {
			dto.setMidNull( true );
		}
		
		dto.setCoordinates( rs.getString( COLUMN_COORDINATES ) );
		dto.setSid( rs.getInt( COLUMN_SID ) );
		if (rs.wasNull()) {
			dto.setSidNull( true );
		}
		
		dto.setCid( rs.getInt( COLUMN_CID ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(TblHotspots dto)
	{
	}

	/** 
	 * Returns all rows from the TBL_HotSpots table that match the specified arbitrary SQL statement
	 */
	public TblHotspots[] findByDynamicSelect(String sql, Object[] sqlParams) throws TblHotspotsDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TblHotspotsDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the TBL_HotSpots table that match the specified arbitrary SQL statement
	 */
	public TblHotspots[] findByDynamicWhere(String sql, Object[] sqlParams) throws TblHotspotsDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TblHotspotsDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	@Override
	public void delete(TblHotspots pk) throws TblHotspotsDaoException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void update(TblHotspotsPk pk, TblHotspots dto)
			throws TblHotspotsDaoException {
		// TODO Auto-generated method stub
		
	}

}
