/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.cmu.cc.slh.jdbc;

import edu.cmu.cc.slh.dao.*;
import edu.cmu.cc.slh.factory.*;
import edu.cmu.cc.slh.dto.*;
import edu.cmu.cc.slh.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class TblWarehouseDaoImpl extends AbstractDAO implements TblWarehouseDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT WID, Address, UID FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( WID, Address, UID ) VALUES ( ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET WID = ?, Address = ?, UID = ? WHERE WID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE WID = ?";

	/** 
	 * Index of column WID
	 */
	protected static final int COLUMN_WID = 1;

	/** 
	 * Index of column Address
	 */
	protected static final int COLUMN_ADDRESS = 2;

	/** 
	 * Index of column UID
	 */
	protected static final int COLUMN_UID = 3;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 3;

	/** 
	 * Index of primary-key column WID
	 */
	protected static final int PK_COLUMN_WID = 1;

	/** 
	 * Inserts a new row in the TBL_Warehouse table.
	 */
	public TblWarehousePk insert(TblWarehouse dto) throws TblWarehouseDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT, Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			stmt.setInt( index++, dto.getWid() );
			stmt.setString( index++, dto.getAddress() );
			if (dto.isUidNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getUid() );
			}
		
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setWid( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TblWarehouseDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the TBL_Warehouse table.
	 */
	public void update(TblWarehousePk pk, TblWarehouse dto) throws TblWarehouseDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getWid() );
			stmt.setString( index++, dto.getAddress() );
			if (dto.isUidNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getUid() );
			}
		
			stmt.setInt( 4, pk.getWid() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TblWarehouseDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the TBL_Warehouse table.
	 */
	public void delete(TblWarehousePk pk) throws TblWarehouseDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getWid() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TblWarehouseDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the TBL_Warehouse table that matches the specified primary-key value.
	 */
	public TblWarehouse findByPrimaryKey(TblWarehousePk pk) throws TblWarehouseDaoException
	{
		return findByPrimaryKey( pk.getWid() );
	}

	/** 
	 * Returns all rows from the TBL_Warehouse table that match the criteria 'WID = :wid'.
	 */
	public TblWarehouse findByPrimaryKey(int wid) throws TblWarehouseDaoException
	{
		TblWarehouse ret[] = findByDynamicSelect( SQL_SELECT + " WHERE WID = ?", new Object[] {  new Integer(wid) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the TBL_Warehouse table that match the criteria ''.
	 */
	public TblWarehouse[] findAll() throws TblWarehouseDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY WID", null );
	}

	/** 
	 * Returns all rows from the TBL_Warehouse table that match the criteria 'UID = :uid'.
	 */
	public TblWarehouse[] findByTblManagers(int uid) throws TblWarehouseDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE UID = ?", new Object[] {  new Integer(uid) } );
	}

	/** 
	 * Returns all rows from the TBL_Warehouse table that match the criteria 'WID = :wid'.
	 */
	public TblWarehouse[] findWhereWidEquals(int wid) throws TblWarehouseDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE WID = ? ORDER BY WID", new Object[] {  new Integer(wid) } );
	}

	/** 
	 * Returns all rows from the TBL_Warehouse table that match the criteria 'Address = :address'.
	 */
	public TblWarehouse[] findWhereAddressEquals(String address) throws TblWarehouseDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Address = ? ORDER BY Address", new Object[] { address } );
	}

	/** 
	 * Returns all rows from the TBL_Warehouse table that match the criteria 'UID = :uid'.
	 */
	public TblWarehouse[] findWhereUidEquals(int uid) throws TblWarehouseDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE UID = ? ORDER BY UID", new Object[] {  new Integer(uid) } );
	}

	/**
	 * Method 'TblWarehouseDaoImpl'
	 * 
	 */
	public TblWarehouseDaoImpl()
	{
	}

	/**
	 * Method 'TblWarehouseDaoImpl'
	 * 
	 * @param userConn
	 */
	public TblWarehouseDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "SLH_Web_DB.TBL_Warehouse";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected TblWarehouse fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			TblWarehouse dto = new TblWarehouse();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected TblWarehouse[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			TblWarehouse dto = new TblWarehouse();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		TblWarehouse ret[] = new TblWarehouse[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(TblWarehouse dto, ResultSet rs) throws SQLException
	{
		dto.setWid( rs.getInt( COLUMN_WID ) );
		dto.setAddress( rs.getString( COLUMN_ADDRESS ) );
		dto.setUid( rs.getInt( COLUMN_UID ) );
		if (rs.wasNull()) {
			dto.setUidNull( true );
		}
		
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(TblWarehouse dto)
	{
	}

	/** 
	 * Returns all rows from the TBL_Warehouse table that match the specified arbitrary SQL statement
	 */
	public TblWarehouse[] findByDynamicSelect(String sql, Object[] sqlParams) throws TblWarehouseDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TblWarehouseDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the TBL_Warehouse table that match the specified arbitrary SQL statement
	 */
	public TblWarehouse[] findByDynamicWhere(String sql, Object[] sqlParams) throws TblWarehouseDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TblWarehouseDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
