/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.cmu.cc.slh.dao;

import edu.cmu.cc.slh.dto.*;
import edu.cmu.cc.slh.exceptions.*;

public interface TblManagersDao
{
	/** 
	 * Inserts a new row in the TBL_Managers table.
	 */
	public TblManagersPk insert(TblManagers dto) throws TblManagersDaoException;

	/** 
	 * Updates a single row in the TBL_Managers table.
	 */
	public void update(TblManagersPk pk, TblManagers dto) throws TblManagersDaoException;

	/** 
	 * Deletes a single row in the TBL_Managers table.
	 */
	public void delete(TblManagersPk pk) throws TblManagersDaoException;

	/** 
	 * Returns the rows from the TBL_Managers table that matches the specified primary-key value.
	 */
	public TblManagers findByPrimaryKey(TblManagersPk pk) throws TblManagersDaoException;

	/** 
	 * Returns all rows from the TBL_Managers table that match the criteria 'UID = :uid'.
	 */
	public TblManagers findByPrimaryKey(int uid) throws TblManagersDaoException;

	/** 
	 * Returns all rows from the TBL_Managers table that match the criteria ''.
	 */
	public TblManagers[] findAll() throws TblManagersDaoException;

	/** 
	 * Returns all rows from the TBL_Managers table that match the criteria 'UID = :uid'.
	 */
	public TblManagers[] findWhereUidEquals(int uid) throws TblManagersDaoException;

	/** 
	 * Returns all rows from the TBL_Managers table that match the criteria 'FirstName = :firstName'.
	 */
	public TblManagers[] findWhereFirstNameEquals(String firstName) throws TblManagersDaoException;

	/** 
	 * Returns all rows from the TBL_Managers table that match the criteria 'LastName = :lastName'.
	 */
	public TblManagers[] findWhereLastNameEquals(String lastName) throws TblManagersDaoException;

	/** 
	 * Returns all rows from the TBL_Managers table that match the criteria 'Username = :username'.
	 */
	public TblManagers[] findWhereUsernameEquals(String username) throws TblManagersDaoException;

	/** 
	 * Returns all rows from the TBL_Managers table that match the criteria 'Password = :password'.
	 */
	public TblManagers[] findWherePasswordEquals(String password) throws TblManagersDaoException;

	public TblManagers findWhereUsernamePassEquals(String username, String password) throws TblManagersDaoException;
	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the TBL_Managers table that match the specified arbitrary SQL statement
	 */
	public TblManagers[] findByDynamicSelect(String sql, Object[] sqlParams) throws TblManagersDaoException;

	/** 
	 * Returns all rows from the TBL_Managers table that match the specified arbitrary SQL statement
	 */
	public TblManagers[] findByDynamicWhere(String sql, Object[] sqlParams) throws TblManagersDaoException;

}
