/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.cmu.cc.slh.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the TBL_Categories table.
 */
public class TblCategoriesPk implements Serializable
{
	protected int sid;

	/** 
	 * This attribute represents whether the primitive attribute sid is null.
	 */
	protected boolean sidNull;

	/** 
	 * Sets the value of sid
	 */
	public void setSid(int sid)
	{
		this.sid = sid;
	}

	/** 
	 * Gets the value of sid
	 */
	public int getSid()
	{
		return sid;
	}

	/**
	 * Method 'TblCategoriesPk'
	 * 
	 */
	public TblCategoriesPk()
	{
	}

	/**
	 * Method 'TblCategoriesPk'
	 * 
	 * @param sid
	 */
	public TblCategoriesPk(final int sid)
	{
		this.sid = sid;
	}

	/** 
	 * Sets the value of sidNull
	 */
	public void setSidNull(boolean sidNull)
	{
		this.sidNull = sidNull;
	}

	/** 
	 * Gets the value of sidNull
	 */
	public boolean isSidNull()
	{
		return sidNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof TblCategoriesPk)) {
			return false;
		}
		
		final TblCategoriesPk _cast = (TblCategoriesPk) _other;
		if (sid != _cast.sid) {
			return false;
		}
		
		if (sidNull != _cast.sidNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + sid;
		_hashCode = 29 * _hashCode + (sidNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.cmu.cc.slh.dto.TblCategoriesPk: " );
		ret.append( "sid=" + sid );
		return ret.toString();
	}

}
