/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.cmu.cc.slh.dto;

import edu.cmu.cc.slh.dao.*;
import edu.cmu.cc.slh.factory.*;
import edu.cmu.cc.slh.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class TblCategories implements Serializable
{
	/** 
	 * This attribute maps to the column SID in the TBL_Categories table.
	 */
	protected int sid;

	/** 
	 * This attribute maps to the column Name in the TBL_Categories table.
	 */
	protected String name;

	/**
	 * Method 'TblCategories'
	 * 
	 */
	public TblCategories()
	{
	}

	/**
	 * Method 'getSid'
	 * 
	 * @return int
	 */
	public int getSid()
	{
		return sid;
	}

	/**
	 * Method 'setSid'
	 * 
	 * @param sid
	 */
	public void setSid(int sid)
	{
		this.sid = sid;
	}

	/**
	 * Method 'getName'
	 * 
	 * @return String
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Method 'setName'
	 * 
	 * @param name
	 */
	public void setName(String name)
	{
		this.name = name;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof TblCategories)) {
			return false;
		}
		
		final TblCategories _cast = (TblCategories) _other;
		if (sid != _cast.sid) {
			return false;
		}
		
		if (name == null ? _cast.name != name : !name.equals( _cast.name )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + sid;
		if (name != null) {
			_hashCode = 29 * _hashCode + name.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return TblCategoriesPk
	 */
	public TblCategoriesPk createPk()
	{
		return new TblCategoriesPk(sid);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.cmu.cc.slh.dto.TblCategories: " );
		ret.append( "sid=" + sid );
		ret.append( ", name=" + name );
		return ret.toString();
	}

}
