/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.cmu.cc.slh.dto;

import edu.cmu.cc.slh.dao.*;
import edu.cmu.cc.slh.factory.*;
import edu.cmu.cc.slh.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class TblFloormaps implements Serializable
{
	/** 
	 * This attribute maps to the column ID in the TBL_FloorMaps table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column WID in the TBL_FloorMaps table.
	 */
	protected int wid;

	/** 
	 * This attribute represents whether the primitive attribute wid is null.
	 */
	protected boolean widNull = true;

	/** 
	 * This attribute maps to the column Path in the TBL_FloorMaps table.
	 */
	protected String path;

	/** 
	 * This attribute maps to the column Width in the TBL_FloorMaps table.
	 */
	protected String width;

	/** 
	 * This attribute maps to the column Version in the TBL_FloorMaps table.
	 */
	protected int version;

	/** 
	 * This attribute represents whether the primitive attribute version is null.
	 */
	protected boolean versionNull = true;

	/**
	 * Method 'TblFloormaps'
	 * 
	 */
	public TblFloormaps()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getWid'
	 * 
	 * @return int
	 */
	public int getWid()
	{
		return wid;
	}

	/**
	 * Method 'setWid'
	 * 
	 * @param wid
	 */
	public void setWid(int wid)
	{
		this.wid = wid;
		this.widNull = false;
	}

	/**
	 * Method 'setWidNull'
	 * 
	 * @param value
	 */
	public void setWidNull(boolean value)
	{
		this.widNull = value;
	}

	/**
	 * Method 'isWidNull'
	 * 
	 * @return boolean
	 */
	public boolean isWidNull()
	{
		return widNull;
	}

	/**
	 * Method 'getPath'
	 * 
	 * @return String
	 */
	public String getPath()
	{
		return path;
	}

	/**
	 * Method 'setPath'
	 * 
	 * @param path
	 */
	public void setPath(String path)
	{
		this.path = path;
	}

	/**
	 * Method 'getWidth'
	 * 
	 * @return String
	 */
	public String getWidth()
	{
		return width;
	}

	/**
	 * Method 'setWidth'
	 * 
	 * @param width
	 */
	public void setWidth(String width)
	{
		this.width = width;
	}

	/**
	 * Method 'getVersion'
	 * 
	 * @return int
	 */
	public int getVersion()
	{
		return version;
	}

	/**
	 * Method 'setVersion'
	 * 
	 * @param version
	 */
	public void setVersion(int version)
	{
		this.version = version;
		this.versionNull = false;
	}

	/**
	 * Method 'setVersionNull'
	 * 
	 * @param value
	 */
	public void setVersionNull(boolean value)
	{
		this.versionNull = value;
	}

	/**
	 * Method 'isVersionNull'
	 * 
	 * @return boolean
	 */
	public boolean isVersionNull()
	{
		return versionNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof TblFloormaps)) {
			return false;
		}
		
		final TblFloormaps _cast = (TblFloormaps) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (wid != _cast.wid) {
			return false;
		}
		
		if (widNull != _cast.widNull) {
			return false;
		}
		
		if (path == null ? _cast.path != path : !path.equals( _cast.path )) {
			return false;
		}
		
		if (width == null ? _cast.width != width : !width.equals( _cast.width )) {
			return false;
		}
		
		if (version != _cast.version) {
			return false;
		}
		
		if (versionNull != _cast.versionNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + wid;
		_hashCode = 29 * _hashCode + (widNull ? 1 : 0);
		if (path != null) {
			_hashCode = 29 * _hashCode + path.hashCode();
		}
		
		if (width != null) {
			_hashCode = 29 * _hashCode + width.hashCode();
		}
		
		_hashCode = 29 * _hashCode + version;
		_hashCode = 29 * _hashCode + (versionNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return TblFloormapsPk
	 */
	public TblFloormapsPk createPk()
	{
		return new TblFloormapsPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.cmu.cc.slh.dto.TblFloormaps: " );
		ret.append( "id=" + id );
		ret.append( ", wid=" + wid );
		ret.append( ", path=" + path );
		ret.append( ", width=" + width );
		ret.append( ", version=" + version );
		return ret.toString();
	}

}
