/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.cmu.cc.slh.dto;

import edu.cmu.cc.slh.dao.*;
import edu.cmu.cc.slh.factory.*;
import edu.cmu.cc.slh.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class TblHotspots implements Serializable
{
	/** 
	 * This attribute maps to the column MID in the TBL_HotSpots table.
	 */
	protected int mid;

	/** 
	 * This attribute represents whether the primitive attribute mid is null.
	 */
	protected boolean midNull = true;

	/** 
	 * This attribute maps to the column Coordinates in the TBL_HotSpots table.
	 */
	protected String coordinates;

	/** 
	 * This attribute maps to the column SID in the TBL_HotSpots table.
	 */
	protected int sid;

	/** 
	 * This attribute represents whether the primitive attribute sid is null.
	 */
	protected boolean sidNull = true;

	/** 
	 * This attribute maps to the column CID in the TBL_HotSpots table.
	 */
	protected int cid;

	/**
	 * Method 'TblHotspots'
	 * 
	 */
	public TblHotspots()
	{
	}

	/**
	 * Method 'getMid'
	 * 
	 * @return int
	 */
	public int getMid()
	{
		return mid;
	}

	/**
	 * Method 'setMid'
	 * 
	 * @param mid
	 */
	public void setMid(int mid)
	{
		this.mid = mid;
		this.midNull = false;
	}

	/**
	 * Method 'setMidNull'
	 * 
	 * @param value
	 */
	public void setMidNull(boolean value)
	{
		this.midNull = value;
	}

	/**
	 * Method 'isMidNull'
	 * 
	 * @return boolean
	 */
	public boolean isMidNull()
	{
		return midNull;
	}

	/**
	 * Method 'getCoordinates'
	 * 
	 * @return String
	 */
	public String getCoordinates()
	{
		return coordinates;
	}

	/**
	 * Method 'setCoordinates'
	 * 
	 * @param coordinates
	 */
	public void setCoordinates(String coordinates)
	{
		this.coordinates = coordinates;
	}

	/**
	 * Method 'getSid'
	 * 
	 * @return int
	 */
	public int getSid()
	{
		return sid;
	}

	/**
	 * Method 'setSid'
	 * 
	 * @param sid
	 */
	public void setSid(int sid)
	{
		this.sid = sid;
		this.sidNull = false;
	}

	/**
	 * Method 'setSidNull'
	 * 
	 * @param value
	 */
	public void setSidNull(boolean value)
	{
		this.sidNull = value;
	}

	/**
	 * Method 'isSidNull'
	 * 
	 * @return boolean
	 */
	public boolean isSidNull()
	{
		return sidNull;
	}

	/**
	 * Method 'getCid'
	 * 
	 * @return int
	 */
	public int getCid()
	{
		return cid;
	}

	/**
	 * Method 'setCid'
	 * 
	 * @param cid
	 */
	public void setCid(int cid)
	{
		this.cid = cid;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof TblHotspots)) {
			return false;
		}
		
		final TblHotspots _cast = (TblHotspots) _other;
		if (mid != _cast.mid) {
			return false;
		}
		
		if (midNull != _cast.midNull) {
			return false;
		}
		
		if (coordinates == null ? _cast.coordinates != coordinates : !coordinates.equals( _cast.coordinates )) {
			return false;
		}
		
		if (sid != _cast.sid) {
			return false;
		}
		
		if (sidNull != _cast.sidNull) {
			return false;
		}
		
		if (cid != _cast.cid) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + mid;
		_hashCode = 29 * _hashCode + (midNull ? 1 : 0);
		if (coordinates != null) {
			_hashCode = 29 * _hashCode + coordinates.hashCode();
		}
		
		_hashCode = 29 * _hashCode + sid;
		_hashCode = 29 * _hashCode + (sidNull ? 1 : 0);
		_hashCode = 29 * _hashCode + cid;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return TblHotspotsPk
	 */
	public TblHotspotsPk createPk()
	{
		return new TblHotspotsPk(cid);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.cmu.cc.slh.dto.TblHotspots: " );
		ret.append( "mid=" + mid );
		ret.append( ", coordinates=" + coordinates );
		ret.append( ", sid=" + sid );
		ret.append( ", cid=" + cid );
		return ret.toString();
	}

}
