/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.cmu.cc.slh.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the TBL_HotSpots table.
 */
public class TblHotspotsPk implements Serializable
{
	protected int cid;

	/** 
	 * This attribute represents whether the primitive attribute cid is null.
	 */
	protected boolean cidNull;

	/** 
	 * Sets the value of cid
	 */
	public void setCid(int cid)
	{
		this.cid = cid;
	}

	/** 
	 * Gets the value of cid
	 */
	public int getCid()
	{
		return cid;
	}

	/**
	 * Method 'TblHotspotsPk'
	 * 
	 */
	public TblHotspotsPk()
	{
	}

	/**
	 * Method 'TblHotspotsPk'
	 * 
	 * @param cid
	 */
	public TblHotspotsPk(final int cid)
	{
		this.cid = cid;
	}

	/** 
	 * Sets the value of cidNull
	 */
	public void setCidNull(boolean cidNull)
	{
		this.cidNull = cidNull;
	}

	/** 
	 * Gets the value of cidNull
	 */
	public boolean isCidNull()
	{
		return cidNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof TblHotspotsPk)) {
			return false;
		}
		
		final TblHotspotsPk _cast = (TblHotspotsPk) _other;
		if (cid != _cast.cid) {
			return false;
		}
		
		if (cidNull != _cast.cidNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + cid;
		_hashCode = 29 * _hashCode + (cidNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.cmu.cc.slh.dto.TblHotspotsPk: " );
		ret.append( "cid=" + cid );
		return ret.toString();
	}

}
