/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.cmu.cc.slh.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the TBL_Managers table.
 */
public class TblManagersPk implements Serializable
{
	protected int uid;

	/** 
	 * This attribute represents whether the primitive attribute uid is null.
	 */
	protected boolean uidNull;

	/** 
	 * Sets the value of uid
	 */
	public void setUid(int uid)
	{
		this.uid = uid;
	}

	/** 
	 * Gets the value of uid
	 */
	public int getUid()
	{
		return uid;
	}

	/**
	 * Method 'TblManagersPk'
	 * 
	 */
	public TblManagersPk()
	{
	}

	/**
	 * Method 'TblManagersPk'
	 * 
	 * @param uid
	 */
	public TblManagersPk(final int uid)
	{
		this.uid = uid;
	}

	/** 
	 * Sets the value of uidNull
	 */
	public void setUidNull(boolean uidNull)
	{
		this.uidNull = uidNull;
	}

	/** 
	 * Gets the value of uidNull
	 */
	public boolean isUidNull()
	{
		return uidNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof TblManagersPk)) {
			return false;
		}
		
		final TblManagersPk _cast = (TblManagersPk) _other;
		if (uid != _cast.uid) {
			return false;
		}
		
		if (uidNull != _cast.uidNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + uid;
		_hashCode = 29 * _hashCode + (uidNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.cmu.cc.slh.dto.TblManagersPk: " );
		ret.append( "uid=" + uid );
		return ret.toString();
	}

}
