/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.cmu.cc.slh.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the TBL_Warehouse table.
 */
public class TblWarehousePk implements Serializable
{
	protected int wid;

	/** 
	 * This attribute represents whether the primitive attribute wid is null.
	 */
	protected boolean widNull;

	/** 
	 * Sets the value of wid
	 */
	public void setWid(int wid)
	{
		this.wid = wid;
	}

	/** 
	 * Gets the value of wid
	 */
	public int getWid()
	{
		return wid;
	}

	/**
	 * Method 'TblWarehousePk'
	 * 
	 */
	public TblWarehousePk()
	{
	}

	/**
	 * Method 'TblWarehousePk'
	 * 
	 * @param wid
	 */
	public TblWarehousePk(final int wid)
	{
		this.wid = wid;
	}

	/** 
	 * Sets the value of widNull
	 */
	public void setWidNull(boolean widNull)
	{
		this.widNull = widNull;
	}

	/** 
	 * Gets the value of widNull
	 */
	public boolean isWidNull()
	{
		return widNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof TblWarehousePk)) {
			return false;
		}
		
		final TblWarehousePk _cast = (TblWarehousePk) _other;
		if (wid != _cast.wid) {
			return false;
		}
		
		if (widNull != _cast.widNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + wid;
		_hashCode = 29 * _hashCode + (widNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.cmu.cc.slh.dto.TblWarehousePk: " );
		ret.append( "wid=" + wid );
		return ret.toString();
	}

}
